name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Setup Golang
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - name: Build
        run: make build
      - name: Test
        run: go test ./...

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm
          - os: linux
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Setup Golang
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: go.mod
      - name: Build binary
        run: |
          rm -rf ./bin
          ARCH=${{ matrix.arch }} make build
          mv bin/hyperkv bin/hyperkv-${{ matrix.os }}-${{ matrix.arch }}
      - uses: actions/upload-artifact@v7.0.1
        with:
          name: hyperkv-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/hyperkv-${{ matrix.os }}-${{ matrix.arch }}
          if-no-files-found: error

  publish:
    needs: release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v7.0.1
        with:
          pattern: hyperkv-*
          path: bin
          merge-multiple: true
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/hyperkv-*
