name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build-hyperkv:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm
          - os: linux
            arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1 # v4.1.1
      - name: Setup Golang
        uses: actions/setup-go@v4.1.0 # v4.1.0
        with:
          go-version-file: go.mod
      - name: Build binary
        run: |
          rm -rf ./bin
          ARCH=${{ matrix.arch }} make build
          mv bin/hyperkv bin/hyperkv-${{ matrix.os }}-${{ matrix.arch }}
      - uses: actions/upload-artifact@v3.1.3 # v3.1.3
        with:
          name: hyperkv-${{ matrix.os }}-${{ matrix.arch }}
          path: bin/hyperkv-${{ matrix.os }}-${{ matrix.arch }}
          if-no-files-found: error
  publish:
      runs-on: ubuntu-latest
      needs:
        - build-hyperkv
      permissions:
        contents: write
        pull-requests: write
      steps:
        - name: Download artifacts
          uses: actions/download-artifact@v3.0.2 # v3.0.2
          with:
            path: ./artifacts
        - name: Publish release
          uses: softprops/action-gh-release@v1 # v1
          with:
            files: |
              ./artifacts/hyperkv-*-*/*